# Generated by Django 4.2.30 on 2026-06-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0242_space_household_setup_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD', 'Member added'), ('REMOVE', 'Member removed'), ('UPDATE', 'Member updated'), ('GROUP_CHANGE', 'Groups changed'), ('SELF_LEAVE', 'Member left')], max_length=32)),
                ('space_id', models.IntegerField(db_index=True)),
                ('target_user_id', models.IntegerField(db_index=True)),
                ('target_username', models.CharField(blank=True, max_length=150)),
                ('actor_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('old_groups', models.JSONField(blank=True, default=list)),
                ('new_groups', models.JSONField(blank=True, default=list)),
                ('old_household_id', models.IntegerField(blank=True, null=True)),
                ('new_household_id', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['space_id', '-created_at'], name='cookbook_pe_space_i_fd9d33_idx'), models.Index(fields=['target_user_id', '-created_at'], name='cookbook_pe_target__1019d4_idx'), models.Index(fields=['actor_user_id', '-created_at'], name='cookbook_pe_actor_u_8b64b6_idx')],
            },
        ),
    ]
