# Generated by Django 5.2.13 on 2026-06-11 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0242_space_household_setup_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritioninformation',
            name='confidence_score',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Nutrition estimation confidence score 0-100', max_digits=5),
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='low_confidence_ingredients',
            field=models.JSONField(blank=True, default=list, help_text='List of ingredients flagged for low confidence'),
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='missing_ingredients',
            field=models.JSONField(blank=True, default=list, help_text='List of ingredients with missing nutrition data'),
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Flag indicating this nutrition data requires manual review'),
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='review_comment',
            field=models.TextField(blank=True, help_text='Comment left during review', null=True),
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto Approved')], default='AUTO_APPROVED', help_text='Current review status', max_length=32),
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='confidence_score',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Property value confidence score 0-100', max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='data_source',
            field=models.CharField(default='MANUAL', help_text='Source of this property data: MANUAL, FDC, OPEN_DATA, AI', max_length=64),
        ),
        migrations.AddField(
            model_name='property',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Flag indicating this property requires manual review'),
        ),
    ]
