# Generated by Django 5.2.13 on 2026-06-11 21:39

import cookbook.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0242_space_household_setup_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheRefreshTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('UNIT_MERGE', 'Unit Merge'), ('UNIT_DELETE', 'Unit Delete'), ('UNIT_SAVE', 'Unit Save')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('message', models.TextField(blank=True, default='')),
                ('source_unit_id', models.IntegerField(blank=True, null=True)),
                ('target_unit_id', models.IntegerField(blank=True, null=True)),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('batch_size', models.IntegerField(default=100)),
                ('batch_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.space')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['space', 'status'], name='cookbook_ca_space_i_33c5fc_idx'), models.Index(fields=['-created_at'], name='cookbook_ca_created_4f05ae_idx')],
            },
            bases=(models.Model, cookbook.models.PermissionModelMixin),
        ),
    ]
