# Generated by Django 5.2.13 on 2026-06-11 22:56

import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0243_recipebookentrychangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipebookentrychangerequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='recipebookentrychangerequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ChangeRequestDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_type', models.CharField(choices=[('ADD', 'Add Request'), ('RESUBMIT', 'Resubmit Request')], default='ADD', max_length=16)),
                ('recipe_id', models.IntegerField(blank=True, null=True)),
                ('recipe_name', models.CharField(blank=True, default='', max_length=256)),
                ('note', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_request_drafts', to='cookbook.recipebook')),
                ('change_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='cookbook.recipebookentrychangerequest')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_request_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('change_request__isnull', True)), fields=('user', 'book', 'draft_type'), name='unique_draft_per_user_book_type'), models.UniqueConstraint(condition=models.Q(('change_request__isnull', False)), fields=('user', 'change_request'), name='unique_draft_per_user_change_request')],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('change_request_draft'), models.Model),
        ),
    ]
