# Generated by Django 5.2.13 on 2026-06-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0243_cacherefreshtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacherefreshtask',
            name='cache_patterns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cacherefreshtask',
            name='last_processed_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cacherefreshtask',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='cacherefreshtask',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cacherefreshtask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=32),
        ),
    ]
