# Generated by Django 5.2.13 on 2026-06-11 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0244_cacherefreshtask_cache_patterns_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cacherefreshtask',
            name='merged_into_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_tasks', to='cookbook.cacherefreshtask'),
        ),
        migrations.AlterField(
            model_name='cacherefreshtask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=32),
        ),
        migrations.AddIndex(
            model_name='cacherefreshtask',
            index=models.Index(fields=['space', 'source_unit_id', 'status'], name='cookbook_ca_space_i_b776ab_idx'),
        ),
    ]
