/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeBookEntryChangeRequest } from './RecipeBookEntryChangeRequest';
import {
    RecipeBookEntryChangeRequestFromJSON,
    RecipeBookEntryChangeRequestFromJSONTyped,
    RecipeBookEntryChangeRequestToJSON,
} from './RecipeBookEntryChangeRequest';

/**
 * 
 * @export
 * @interface PaginatedRecipeBookEntryChangeRequestList
 */
export interface PaginatedRecipeBookEntryChangeRequestList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedRecipeBookEntryChangeRequestList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRecipeBookEntryChangeRequestList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRecipeBookEntryChangeRequestList
     */
    previous?: string;
    /**
     * 
     * @type {Array<RecipeBookEntryChangeRequest>}
     * @memberof PaginatedRecipeBookEntryChangeRequestList
     */
    results: Array<RecipeBookEntryChangeRequest>;
    /**
     * 
     * @type {Date}
     * @memberof PaginatedRecipeBookEntryChangeRequestList
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the PaginatedRecipeBookEntryChangeRequestList interface.
 */
export function instanceOfPaginatedRecipeBookEntryChangeRequestList(value: object): value is PaginatedRecipeBookEntryChangeRequestList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedRecipeBookEntryChangeRequestListFromJSON(json: any): PaginatedRecipeBookEntryChangeRequestList {
    return PaginatedRecipeBookEntryChangeRequestListFromJSONTyped(json, false);
}

export function PaginatedRecipeBookEntryChangeRequestListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedRecipeBookEntryChangeRequestList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(RecipeBookEntryChangeRequestFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function PaginatedRecipeBookEntryChangeRequestListToJSON(value?: PaginatedRecipeBookEntryChangeRequestList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(RecipeBookEntryChangeRequestToJSON)),
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
    };
}

