/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeBook } from './RecipeBook';
import {
    RecipeBookFromJSON,
    RecipeBookFromJSONTyped,
    RecipeBookToJSON,
} from './RecipeBook';
import type { RecipeOverview } from './RecipeOverview';
import {
    RecipeOverviewFromJSON,
    RecipeOverviewFromJSONTyped,
    RecipeOverviewToJSON,
} from './RecipeOverview';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface PatchedRecipeBookEntryChangeRequest
 */
export interface PatchedRecipeBookEntryChangeRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedRecipeBookEntryChangeRequest
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedRecipeBookEntryChangeRequest
     */
    book?: number;
    /**
     * 
     * @type {RecipeBook}
     * @memberof PatchedRecipeBookEntryChangeRequest
     */
    readonly bookContent?: RecipeBook;
    /**
     * 
     * @type {number}
     * @memberof PatchedRecipeBookEntryChangeRequest
     */
    recipe?: number;
    /**
     * 
     * @type {RecipeOverview}
     * @memberof PatchedRecipeBookEntryChangeRequest
     */
    readonly recipeContent?: RecipeOverview;
    /**
     * 
     * @type {string}
     * @memberof PatchedRecipeBookEntryChangeRequest
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRecipeBookEntryChangeRequest
     */
    readonly status?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRecipeBookEntryChangeRequest
     */
    note?: string;
    /**
     * 
     * @type {User}
     * @memberof PatchedRecipeBookEntryChangeRequest
     */
    readonly createdBy?: User;
    /**
     * 
     * @type {User}
     * @memberof PatchedRecipeBookEntryChangeRequest
     */
    readonly reviewedBy?: User | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedRecipeBookEntryChangeRequest
     */
    readonly reviewNote?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRecipeBookEntryChangeRequest
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRecipeBookEntryChangeRequest
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRecipeBookEntryChangeRequest
     */
    readonly reviewedAt?: Date | null;
}

/**
 * Check if a given object implements the PatchedRecipeBookEntryChangeRequest interface.
 */
export function instanceOfPatchedRecipeBookEntryChangeRequest(value: object): value is PatchedRecipeBookEntryChangeRequest {
    return true;
}

export function PatchedRecipeBookEntryChangeRequestFromJSON(json: any): PatchedRecipeBookEntryChangeRequest {
    return PatchedRecipeBookEntryChangeRequestFromJSONTyped(json, false);
}

export function PatchedRecipeBookEntryChangeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedRecipeBookEntryChangeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'book': json['book'] == null ? undefined : json['book'],
        'bookContent': json['book_content'] == null ? undefined : RecipeBookFromJSON(json['book_content']),
        'recipe': json['recipe'] == null ? undefined : json['recipe'],
        'recipeContent': json['recipe_content'] == null ? undefined : RecipeOverviewFromJSON(json['recipe_content']),
        'action': json['action'] == null ? undefined : json['action'],
        'status': json['status'] == null ? undefined : json['status'],
        'note': json['note'] == null ? undefined : json['note'],
        'createdBy': json['created_by'] == null ? undefined : UserFromJSON(json['created_by']),
        'reviewedBy': json['reviewed_by'] == null ? undefined : UserFromJSON(json['reviewed_by']),
        'reviewNote': json['review_note'] == null ? undefined : json['review_note'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'reviewedAt': json['reviewed_at'] == null ? undefined : (json['reviewed_at'] == null ? null : new Date(json['reviewed_at'])),
    };
}

export function PatchedRecipeBookEntryChangeRequestToJSON(value?: Omit<PatchedRecipeBookEntryChangeRequest, 'bookContent'|'recipeContent'|'status'|'createdBy'|'reviewedBy'|'reviewNote'|'createdAt'|'updatedAt'|'reviewedAt'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'book': value['book'],
        'recipe': value['recipe'],
        'action': value['action'],
        'note': value['note'],
    };
}

