/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeBook } from './RecipeBook';
import {
    RecipeBookFromJSON,
    RecipeBookFromJSONTyped,
    RecipeBookToJSON,
} from './RecipeBook';
import type { RecipeOverview } from './RecipeOverview';
import {
    RecipeOverviewFromJSON,
    RecipeOverviewFromJSONTyped,
    RecipeOverviewToJSON,
} from './RecipeOverview';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface RecipeBookEntryChangeRequest
 */
export interface RecipeBookEntryChangeRequest {
    /**
     * 
     * @type {number}
     * @memberof RecipeBookEntryChangeRequest
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof RecipeBookEntryChangeRequest
     */
    book: number;
    /**
     * 
     * @type {RecipeBook}
     * @memberof RecipeBookEntryChangeRequest
     */
    readonly bookContent?: RecipeBook;
    /**
     * 
     * @type {number}
     * @memberof RecipeBookEntryChangeRequest
     */
    recipe: number;
    /**
     * 
     * @type {RecipeOverview}
     * @memberof RecipeBookEntryChangeRequest
     */
    readonly recipeContent?: RecipeOverview;
    /**
     * 
     * @type {string}
     * @memberof RecipeBookEntryChangeRequest
     */
    action?: RecipeBookEntryChangeRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof RecipeBookEntryChangeRequest
     */
    readonly status?: RecipeBookEntryChangeRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof RecipeBookEntryChangeRequest
     */
    note?: string;
    /**
     * 
     * @type {User}
     * @memberof RecipeBookEntryChangeRequest
     */
    readonly createdBy?: User;
    /**
     * 
     * @type {User}
     * @memberof RecipeBookEntryChangeRequest
     */
    readonly reviewedBy?: User | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeBookEntryChangeRequest
     */
    readonly reviewNote?: string;
    /**
     * 
     * @type {Date}
     * @memberof RecipeBookEntryChangeRequest
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RecipeBookEntryChangeRequest
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RecipeBookEntryChangeRequest
     */
    readonly reviewedAt?: Date | null;
}

/**
 * @export
 */
export const RecipeBookEntryChangeRequestActionEnum = {
    Add: 'ADD',
    Remove: 'REMOVE'
} as const;
export type RecipeBookEntryChangeRequestActionEnum = typeof RecipeBookEntryChangeRequestActionEnum[keyof typeof RecipeBookEntryChangeRequestActionEnum];

/**
 * @export
 */
export const RecipeBookEntryChangeRequestStatusEnum = {
    Pending: 'PENDING',
    Approved: 'APPROVED',
    Rejected: 'REJECTED',
    Withdrawn: 'WITHDRAWN'
} as const;
export type RecipeBookEntryChangeRequestStatusEnum = typeof RecipeBookEntryChangeRequestStatusEnum[keyof typeof RecipeBookEntryChangeRequestStatusEnum];


/**
 * Check if a given object implements the RecipeBookEntryChangeRequest interface.
 */
export function instanceOfRecipeBookEntryChangeRequest(value: object): value is RecipeBookEntryChangeRequest {
    if (!('book' in value) || value['book'] === undefined) return false;
    if (!('recipe' in value) || value['recipe'] === undefined) return false;
    return true;
}

export function RecipeBookEntryChangeRequestFromJSON(json: any): RecipeBookEntryChangeRequest {
    return RecipeBookEntryChangeRequestFromJSONTyped(json, false);
}

export function RecipeBookEntryChangeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeBookEntryChangeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'book': json['book'],
        'bookContent': json['book_content'] == null ? undefined : RecipeBookFromJSON(json['book_content']),
        'recipe': json['recipe'],
        'recipeContent': json['recipe_content'] == null ? undefined : RecipeOverviewFromJSON(json['recipe_content']),
        'action': json['action'] == null ? undefined : json['action'],
        'status': json['status'] == null ? undefined : json['status'],
        'note': json['note'] == null ? undefined : json['note'],
        'createdBy': json['created_by'] == null ? undefined : UserFromJSON(json['created_by']),
        'reviewedBy': json['reviewed_by'] == null ? undefined : UserFromJSON(json['reviewed_by']),
        'reviewNote': json['review_note'] == null ? undefined : json['review_note'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'reviewedAt': json['reviewed_at'] == null ? undefined : (json['reviewed_at'] == null ? null : new Date(json['reviewed_at'])),
    };
}

export function RecipeBookEntryChangeRequestToJSON(value?: Omit<RecipeBookEntryChangeRequest, 'bookContent'|'recipeContent'|'status'|'createdBy'|'reviewedBy'|'reviewNote'|'createdAt'|'updatedAt'|'reviewedAt'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'book': value['book'],
        'recipe': value['recipe'],
        'action': value['action'],
        'note': value['note'],
    };
}

